version: "3"
services:
  web:
    build: web
    links:
      - api
    ports:
      - 3000:3000
    environment:
      API_HOST: api
  api:
    build: api
    links:
      - db
    depends_on:
      - db
    ports:
      - 5000:5000
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: hertzmedia
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
